"""
This code script compares the small-signal model response to the EMT response 
for all data generated by run.py
"""

# Import libraries
import os
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib
import numpy as np
import polars as pl
import scienceplots
import seaborn as sns


# Helper functions
# ----------------
def simulation_rmse(directory, file, col):
    """Compare SSM and EMT dynamics"""
    emt_df = pl.read_csv(os.path.join(directory, "emt", file))
    ssm_df = pl.read_csv(os.path.join(directory, "ssm", file)).rename({"v_lcl_sh_d":"v_sh_d","v_lcl_sh_q":"v_sh_q"}, strict=False)

    return np.mean( ((ssm_df[col] - emt_df[col])**2).to_numpy())

# Process each simulation
# -----------------------
case_directory = os.path.join(Path(__file__).resolve().parent)
data = []

components = {
    "shunt_parallel_rc": (8, ["v_bus_D", "v_bus_Q"]),
    "branch_series_rl": (8, ["i_br_D", "i_br_Q"]),
    "constant_impedance_loads": (3, ["i_bus_D", "i_bus_Q"]),
    "gfli_16a": (1, ["i_vsc_d","i_vsc_q","v_sh_d","v_sh_q","i_bus_d","i_bus_q"]),
    "gfmi_18a": (1, ["i_vsc_d","i_vsc_q","v_sh_d","v_sh_q","i_bus_d","i_bus_q"]),
}

# 

for generator in ['gfmi_18a_0', 'gfli_16a_0']:
    for reference in ['p_ref', 'q_ref']:
        for amplitude in [-0.15, -0.10, -0.05, 0.05, 0.10, 0.15]:
            # Location of all outputs
            if amplitude < 0:
                simulation_name = f"{generator}-{reference}-minus-{int(100*abs(amplitude))}"
            else:
                simulation_name = f"{generator}-{reference}-plus-{int(100*abs(amplitude))}"

            output_dir = os.path.join(case_directory, "simulations", simulation_name)

            for component, (n, cols) in components.items():
                for i in range(n):
                    file = f"{component}_{i}.csv"
                    
                    for col in cols:
                        
                        row = {
                            "generator": generator, 
                            "reference": reference, 
                            "amplitude": f"$\pm {abs(amplitude)}$",
                            "file": file,
                            "column": col,
                            "rmse":  simulation_rmse(output_dir, file, col)
                        }

                        data.append(row)

df = pl.from_dicts(data)
df = df.with_columns(
    (   "$"
        + pl.col("column").str.slice(0, 1)
        + "_"
        + pl.col("column").str.slice(-1, 1)
        + "$"
    )
    .str.to_lowercase()
    .alias("State")
)

# Plotting settings
plt.style.use(['science','ieee'])
#plt.rcParams['text.usetex'] = False
plt.rc('font',**{'family':'serif','serif':['Times'], 'size': 7})
#plt.rcParams['axes.formatter.useoffset'] = False # this prevent scientific notation in y-axis
linewidth = 0.80

# Color scheme 
purple = "#D7A9E3";
blue = "#8BBEE8";
green = "#A8D5BA";
yellow = "#F3E28D"
holland_mint = [ blue, purple, green, yellow]


fig, ax = plt.subplots(1, 1, figsize=(4.3, 4))

# Create figure
sns.boxplot(
    data=df.to_pandas(), ax=ax,
    y="State", x="rmse",
    fill=False, color='darkgray', linewidth=0.5, zorder=1, showfliers=False)

sns.swarmplot(
    data=df.to_pandas(), ax=ax,
    y="State", x="rmse", hue='amplitude', 
    palette=holland_mint,  dodge=True, size=2.5, zorder=0#, size=2.5
)

sns.move_legend(ax, "upper right", ncol=1, title="Step\namplitude [pu]",   )

ax.legend(handletextpad=0.2, title="Step\namplitude [pu]", edgecolor='k', frameon=True, fancybox=False,)
ax.get_legend().get_frame().set_linewidth(0.5)
ax.get_legend().get_title().set_ha("center")


ax.set_xlabel("")
ax.tick_params(axis="x",direction="in", width=0.5)
ax.tick_params(axis="y",direction="in", width=0.5)
ax.yaxis.set_minor_locator(plt.NullLocator())
plt.xlim(5e-14, 1e-2)
plt.xscale('log')
plt.xlabel("Mean-squared error [pu]")

fig.savefig(os.path.join(case_directory, "boxplot_error_v2.pdf"))